### ISSUE TITLE
Bug: endpoint.get_all_sprints() misapplies the query parameter

### ISSUE THREAD

**Issue by markd-jsr** [princenyeche/jiraone#137]
In the **get_all_sprints** code, if a **query** parameter is applied, the format string in the marked code below applies the **query** value as the _startAt=_ value, which also skews **max_results**. Meanwhile, query is not applied within the REST call at all. 
```
    @classmethod
    def get_all_sprints(
        cls,
        board_id: int,
        query: str = None,
        start_at: int = 0,
        max_results: int = 50,
    ) -> str:
        """Get all Sprint on a Board.

        :param board_id: A board id

        :param start_at: defaults to 0

        :param max_results: defaults to 50

        :param query: A search term

        :return: A string of the url
        """
        if query is not None:

>             return "{}/rest/agile/1.0/board/{}/sprint?startAt={}&maxResults={}".format(
>                 LOGIN.base_url, board_id, query, start_at, max_results

            )
        else:
            return "{}/rest/agile/1.0/board/{}/sprint?startAt={}&maxResults={}".format(
                LOGIN.base_url, board_id, start_at, max_results
            )
```

**Comment by markd-jsr** [comment]
Wow, talk about a fast turnaround time!

**Comment by princenyeche** [comment]
Hey @markd-jsr 

I have applied a fix to the bug. I will be pushing a new version within a couple of hours.

**Comment by princenyeche** [comment]
Fix applied

**Comment by markd-jsr** [comment]
Thanks Prince!

Since I'm needing this call to do Jira analytics, here's some further observations that I have on the, umm, limitations of the 1.0 API call. You might want to work these into your push.

The ../board/_id_/sprint endpoint seems to cap the max_results parameter to 50. I tested this with other values and can verify in the response object. It will respect any value up to 50, but anything above returns with max_results=50 .

Since the function is called get_all_sprints, that's what I'd expect it to do. As it stands now, I need to manage the pagination outside of the function and call it multiple times using the start_at param. Since the response does include the total sprints available, it's not hard to manage this. I have working code if you are interested.

I have question as well. It seems that the sprint endpoint, as well as several others, are only available in the 1.0 API version. Weird. I can't find any documentation for that. Do you have a pointer?

Thanks,
Mark
________________________________

**Comment by princenyeche** [comment]
That's the expected return limit based on Atlassian's REST API 1.0 version for Jira Software. The function `get_all_sprints` requires additional programming to get all sprints through pagination, that's the right way to use it and it applies, to most if not all functions within the `endpoint` class. The reason, I left the endpoint class and its function in its basic form, is to allow the usage in any form necessary by other people to get the data they need. That has been the primary focal point for that class. If I do encounter a use case where these data can be generated and put into a report; then I may consider putting that into the `report` module as part of the `PROJECT` function.

To your question, Atlassian official REST API [document](https://developer.atlassian.com/cloud/jira/software/rest/intro/#introduction) for Jira Software has always been on the 1.0 version and hasn't changed in the longest time. I believe the reason behind the API versioning is to offer different behaviours, so users can choose which behaviour suits their use case. At this point, Jira Software offers a singular behaviour, I believe, that's why there are no other versions for it as compared to Jira which has v2 and v3 respectively with v3 mostly in an experimental phase.

**Comment by markd-jsr** [comment]
I appreciate the insight into the design thinking. Given this, I have a suggestion.

If the pattern on many endpoints is that it will require users to implement pagination, then I suggest to document this fact somewhere in jiraone. I say this because I spent some time trying to understand why max_results wasn't working. That ultimately had me debugging into jiraone implementation to figure out this limit was actually imposed by the Jira API.

Given the name of the function _get_all_..._ and that it has a parameter that seemingly allows to pull more items, my expectation was that I get everything that I needed with a single call. So for the sake of future users and not having them discover the same the hard way, maybe make a note in the documentation -- or better yet an example of using pagination -- and say that it applies throughout the API. 

Thanks for that info on the API. It's definitely not obvious given the way it's laid out that it is defaulting to 1.0. Then again, that's very consistent with how most things are implemented with Atlassian :-)

**Comment by princenyeche** [comment]
Thanks, @markd-jsr for the feedback. I've noted that down and will update the documentation to reflect that implementation part by the user when using the `endpoint` class.
